Upgrade the new microservice build and  modify  the documentation
ome/ansible-role-omero-ms-image-region pull request #2
Opened 2024-04-15 14:45 UTC by khaledk2

2024-04-16 11:05 UTC, khaledk2 commented
@pwalczysko could you please check the documentation?

2024-04-17 16:44 UTC, pwalczysko commented on README.md
>  - omero_ms_image_region_user: 'omero-server': icroservice user, the defaults is omero-server
```suggestion
- omero_ms_image_region_user: Microservice user, the default is `omero-server`
```

Maybe like this ^^^ ? But double-check please, this particular definition seems to be duplicate one line below and the intention is not clear.

2024-04-17 16:44 UTC, pwalczysko commented on README.md
> +- omero_ms_image_region_user: 'omero-server'
```suggestion

```

Maybe remove as it is a duplication ? Please check.

2024-04-17 16:58 UTC, pwalczysko commented on README.md
> +- The bio-format version for both the microservice and Omero-Server should be the same
```suggestion
- The Bio-Formats version of the microservice should match the Bio-Formats version of the OMERO.server
```
See 
https://omero.readthedocs.io/en/stable/sysadmins/unix/server-installation.html for motivation of OMERO.server spelling.

2024-04-17 17:01 UTC, pwalczysko commented on README.md
> +- Also, in case of using ngff data, the version of OMEZarrReader should be the same for both of the Microsevice and the Omero-Server.
Please see https://github.com/khaledk2/ansible-role-omero-ms-image-region/pull/2/files#r1569168184 for OMERO.server spelling - please unify capitalization of "Microservice" (also, here is a typo "Microsevice", "r" missing) in the whole document.

Further spelling suggestions

NGFF (all capitals, it is an abbreviation)

``Also, in case of using`` -> ``If you use`` (drop the "Also" and simplify the "in case of using")

2024-04-17 17:07 UTC, pwalczysko commented
![Screenshot 2024-04-17 at 18 05 23](https://github.com/khaledk2/ansible-role-omero-ms-image-region/assets/2478303/dfc55cf7-e35c-4549-8e3e-3d62d1d7571b)

I would never use `Omero`, rather either `omero` or `OMERO` -> my preference is OMERO.
Also, for the last linel in the screenshot above, I think we should use the same formulation of the default value of the variable as in the whole document (i.e. ...the default value is ``omero`` rather than using two colons on the same line which is confusing.

2024-04-17 17:24 UTC, pwalczysko commented on defaults/main.yml
> +# Microservice download URL, the user should update it with a version which is compatible with the installed omero-server, i.e.:
```suggestion
# Microservice download URL: update to match Bio-Formats versions of the Microservice and OMERO.server. Also, the OMEZarrReader (if NGFF is used) versions of the Microservice and OMERO.server must match.
```

2024-04-17 17:28 UTC, pwalczysko commented
Reformulate https://github.com/khaledk2/ansible-role-omero-ms-image-region/blob/ac77df6bec9c2125df4b60c90d46b337c1c348ad/defaults/main.yml#L44 please.

``Controls updating the nginx config file (omero-web.conf). If set to false, file does not get updated.``

2024-04-17 17:34 UTC, pwalczysko commented on defaults/main.yml
>  # Log level, it can be info, debug or error
```suggestion
# Log level, allowed values: ``info``, ``debug``,  ``error``
```

2024-04-17 17:35 UTC, pwalczysko requested changes
Couple of suggestions, thank you.

2024-04-18 14:10 UTC, khaledk2 commented
Thank you @pwalczysko  for the feedback.
I have applied all the suggested changes on one commit.

2024-04-19 09:27 UTC, pwalczysko commented
Thank you @khaledk2 - please re-request my review using the button here - I will have another look later

2024-04-26 15:12 UTC, pwalczysko commented on README.md
> +- omero_ms_image_region_db_url: OMERO Database URL
Database -> database (to unify capitalization with the lines below)

2024-04-26 15:13 UTC, pwalczysko commented on README.md
> +- The bio-format version for the Microservice should match the Bio-Formats version of the Omero-Server
Omero-Server -> OMERO.server

2024-04-26 15:14 UTC, pwalczysko commented on README.md
> +- Also, in case of using ngff data, the version of OMEZarrReader should be the same for both of the Microsevice and the Omero-Server.
Please try to simplify the formulation as suggested above and use NGFF (not ngff)

2024-04-26 15:14 UTC, pwalczysko commented on defaults/main.yml
> +# OMERO Database URL
Database -> database

2024-04-26 15:15 UTC, pwalczysko commented on defaults/main.yml
> +# No of the Microservice workers, the default is double the number of processors which the machine has
No -> Number (if you use abbreviation No., you must use the dot as well, otherwise it means negation)

2024-04-26 15:18 UTC, pwalczysko requested changes
I have found 4 more minor issues and please try to reformulate as per https://github.com/khaledk2/ansible-role-omero-ms-image-region/pull/2/files#r1581179670

2024-04-29 15:40 UTC, pwalczysko approved these changes

2024-04-30 09:58 UTC, merged